### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Chris2011** [maltron/kubernetesplugin#1]
Hey,

I saw this plugin and I'm wondering what it is for. So what are the plans for this plugin? Can you please provide some details?

Regards

Chris

**Comment by Chris2011** [comment]
Is it still alive?

**Comment by Chris2011** [comment]
Any news here? @maltron

**Comment by maltron** [comment]
Hey Chris,

   3 years ago, I was considering in developing a NetBeans plug-in to tight integrate with Kubernetes/OpenShift. I was doing some testing and eventually, I've found a similar project. Due the lack of timing, I kind abandoned the whole idea. I am pretty sure the situation today is way different.

Maltron

**Comment by Chris2011** [comment]
Yeah, I think kubernetes got more and more interesting and more usage these days. So this plugin would be very cool. But I can understand the timing issue, I have the same :). Thx for the info and thx for the interesting in doing such a plugin.
